#!/bin/bash

MONGO='/opt/mongo/current/bin/mongo'

$MONGO gam_local --eval "db.user_combat.remove({}); db.user_id_cambatid.remove({});" > /dev/null

if [ "$1" == "1" ]
then
	echo
	echo "*** user_campaign is reserved ***"
	echo
else
$MONGO gam_local --eval "db.user_campaign.remove({});" > /dev/null
$MONGO gam_local --eval "db.user_playstate.remove({});" > /dev/null
fi  #ifend

$MONGO gam_timers_local --eval "db.timerqueue.remove({});" > /dev/null

# del all push msg
redis-cli KEYS "push_msg*" | awk '{print $1}' | xargs redis-cli DEL {} \ > /dev/null

echo 'Done'

