#!/bin/sh

API2_PID=$(ps aux | grep node -w | grep 'run.js api2' | awk '{print $2}')

if [[ -n "$API2_PID" ]]

then

  NI_STR="/bin/node-inspector"

  NI_INFO=$(ps aux | grep $NI_STR | grep -v "grep")

  if [[ $NI_INFO == *$NI_STR* ]]
  then
    NI_PID=$(echo $NI_INFO | awk '{print $2}')
    kill $NI_PID
  fi #ifend

  # launch node-inspector
  node-inspector &
	sleep 1s

  MY_PWD=`cat ~/MyConfigFiles/.password | base64 --decode`
  echo $MY_PWD | sudo -S kill -usr1 $API2_PID

	/usr/bin/open -a "/Applications/Google Chrome.app" 'http://127.0.0.1:8080/debug?port=5858'
else

  echo "api2 svr is NOT running ..."

fi #ifend

