#!/bin/sh

CUR_PATH="`pwd`/"

if [[ $CUR_PATH == *"/Workspace/Projects/gam/"* ]]
then
  pushd $GAM/client_gam && git checkout ./ && popd

else
  echo "Hi, you are not in the correct path."
  echo "CUR_PATH =" $CUR_PATH

fi #ifend

