#!/bin/bash

echo
echo 'start to stop servers ...'

SERVERS_PID=$(ps aux | grep -v "grep" | grep ServerLauncher | awk '{print $2}')

for tmpPid in ${SERVERS_PID};
do
	kill $tmpPid
  echo 'stop' $tmpPid, done.;
done;

