#!/bin/bash

IP_172=$(ifconfig | grep inet\ 172. | awk '{print $2}')

IP_192=$(ifconfig | grep inet\ 192. | awk '{print $2}')

IPs=''

if [[ -n "$IP_172" ]]
then
 IPs=${IP_172}
fi

if [ -n "$IP_192" ]
then
 if [ -n "$IPs" ]
 then
  IPs="${IPs} / ${IP_192}"
 else
  IPs=${IP_192}
 fi
fi

echo $IPs | tr -d '\n' | pbcopy && pbpaste

