#!/bin/sh

NI_STR="/bin/node-inspector"

NI_INFO=$(ps aux | grep $NI_STR | grep -v "grep")

if [[ $NI_INFO == *$NI_STR* ]]
then
  NI_PID=$(echo $NI_INFO | awk '{print $2}')
  kill $NI_PID
fi #ifend

# launch node-inspector
node-inspector &

MY_PWD=`cat ~/MyConfigFiles/.password`

API2_PID=$(ps aux | grep node -w | grep 'run.js api2' | awk '{print $2}')

if [[ -n "$API2_PID" ]]
then
  echo $MY_PWD | sudo -S kill -usr1 $API2_PID
else
  echo "api2 svr is NOT running ..."
fi #ifend

