#!/bin/bash

NODE_PROCESS_NUM=0
MY_PWD=`cat ~/MyConfigFiles/.password`

cd $GAM/sparx_gam

echo $MY_PWD | sudo -S ./scripts/startlocal.sh

until ((NODE_PROCESS_NUM>10))
do
  sleep 0.2s
  NODE_PROCESS_NUM=`ps aux | grep node -w | wc -l`
done

echo ""
ps aux | grep node -w

