#!/bin/bash

SF_TECH_SCREEN_NUM=`screen -ls | grep SF_Tech | wc -l`

if [ $SF_TECH_SCREEN_NUM -eq 1 ]
then
	screen -ls | grep SF_Tech | awk '{print $1}' | awk -F'.' '{print $1}' | xargs kill
fi  #ifend

sleep 1
screen -R SF_Tech   ssh -i ~/.ssh/jcloud_rsa_private_key -D 1080 root@119.28.180.144 -p 5136

