#!/bin/bash

echo -e "CPU/GPU     core: $(vcgencmd measure_volts core)"
echo -e "SDRAM controller: $(vcgencmd measure_volts sdram_c)"
echo -e "SDRAM        i/o: $(vcgencmd measure_volts sdram_i)"
echo -e "SDRAM   physical: $(vcgencmd measure_volts sdram_p)"

echo

# for id in core sdram_c sdram_i sdram_p
# do
# 	echo -e "$id:\t$(vcgencmd measure_volts $id)"
# done
# 
# echo

vcgencmd measure_temp

